### ISSUE TITLE
Controller 

### ISSUE THREAD

**Issue by lmilunovic** [Ladislav92/FallingBlocks-game-Politeh-Java-Project#2]
Problem is, my controller is now separated (function that executes game flow, but it is still logical function, and also I have to make my functions and some fields public to do this, is it a good way? Or should I make getters and setters for all those?

Проблем что моя контрольер функция сейчас сделана отделенно от FallingBlocksGame у новий клас. Но чтобы то сделал надо было поставить все функцие на public и несколько поля тоже. Это правильно или нет ? Извиняюсь за плохой русский.

**Comment by gagarski** [comment]
The idiomatic Java-way is to create getters/setters for fields which are meant to be public. You can easily generate them with your IDE.

**Comment by lmilunovic** [comment]
Я поставлю getters/setters, сейчас код без них потому что я хотел узнать работает ли мой код. Ещё что то надо поменят? Могу вас найти в четверг на факультете ?

**Comment by gagarski** [comment]
Я напишу свои замечания в ближайшее время.

**Comment by gagarski** [comment]
> Могу вас найти в четверг на факультете ?

Да, в обчыное время занятий.
